/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{vue,js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            fontFamily: {
                sans:    ['Inter', 'system-ui', 'sans-serif'],
                display: ['Inter', 'system-ui', 'sans-serif'],
            },
            colors: {
                // Kinetic Stadium design system
                primary:                    '#a93100',
                'on-primary':               '#ffffff',
                'primary-container':        '#d34000',
                'on-primary-container':     '#fffbff',
                'inverse-primary':          '#ffb59e',
                secondary:                  '#006e29',
                'on-secondary':             '#ffffff',
                'secondary-container':      '#5afd7e',
                'on-secondary-container':   '#00732b',
                tertiary:                   '#545b76',
                surface:                    '#f8f9fa',
                'surface-dim':              '#d9dadb',
                'surface-bright':           '#f8f9fa',
                'surface-container-lowest': '#ffffff',
                'surface-container-low':    '#f3f4f5',
                'surface-container':        '#edeeef',
                'surface-container-high':   '#e7e8e9',
                'surface-container-highest':'#e1e3e4',
                'surface-variant':          '#e1e3e4',
                'on-surface':               '#191c1d',
                'on-surface-variant':       '#5c4037',
                'inverse-surface':          '#2e3132',
                'inverse-on-surface':       '#f0f1f2',
                outline:                    '#916f65',
                'outline-variant':          '#e6beb2',
                error:                      '#ba1a1a',
                'on-error':                 '#ffffff',
                'error-container':          '#ffdad6',
                // Legacy aliases so existing components don't break
                ink: {
                    base:  '#191c1d',
                    muted: '#5c4037',
                    light: '#916f65',
                },
            },
            boxShadow: {
                'card':    '0 4px 12px rgba(0,0,0,0.05)',
                'card-lg': '0 8px 24px rgba(0,0,0,0.08)',
                'nav':     '0 -10px 30px rgba(0,0,0,0.06)',
                'fab':     '0 8px 20px rgba(169,49,0,0.25)',
                'premium': '0 4px 12px rgba(0,0,0,0.05)',
                'float':   '0 8px 20px rgba(169,49,0,0.25)',
                'soft':    '0 2px 8px rgba(0,0,0,0.04)',
            },
            borderRadius: {
                DEFAULT: '0.5rem',
                sm:      '0.25rem',
                md:      '0.75rem',
                lg:      '1rem',
                xl:      '1.5rem',
                '2xl':   '1rem',
                '3xl':   '1.5rem',
                full:    '9999px',
            },
        },
    },
    plugins: [],
}
